version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    container_name: statsDb
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-serv
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  stats-server:
    build: stats-server/stats_service
    image: stats-server-image
    container_name: stats_server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-serv
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-main-service
    image: ewm-service_image
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
        - ewm-db
    environment:
      - EWM_MAIN_URL=http://main:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5431/ewm-service

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
